#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Krema Contributors
"""Generate and validate qa-checklist.md coverage totals from its QA entries."""
from __future__ import annotations

import argparse
import collections
import difflib
import pathlib
import re
import sys

AREA_ORDER = ('VIS', 'ITEM', 'PRE', 'CMD', 'SET', 'NOTI', 'KEY')
AREA_NAMES = {
    'VIS': 'Dock display and placement',
    'ITEM': 'Dock items and task management',
    'PRE': 'Window previews',
    'CMD': 'Context menu and global shortcuts',
    'SET': 'Settings',
    'NOTI': 'Notifications and attention indicators',
    'KEY': 'Keyboard and accessibility',
}
PRIORITIES = ('P0', 'P1', 'P2')
AUTOMATION = ('AUTO', 'AUTO-REQ', 'FIXTURE', 'MANUAL')
ITEM_RE = re.compile(r'^#### QA-([A-Z]+)-(\d+):', re.MULTILINE)
PRIORITY_RE = re.compile(r'^- \*\*Priority\*\*: (P[0-2])$', re.MULTILINE)
AUTOMATION_RE = re.compile(r'^- \*\*Automation\*\*: `([^`]+)`', re.MULTILINE)
COVERAGE_RE = re.compile(r'(?s)(## Coverage\n\n)(.*?)(\n\nPriorities are)')


def automation_tag(raw: str) -> str:
    for tag in ('AUTO-REQ', 'AUTO', 'FIXTURE', 'MANUAL'):
        if raw.startswith(tag):
            return tag
    raise ValueError(f'unknown automation tag: {raw!r}')


def parse_items(text: str) -> list[dict[str, str]]:
    matches = list(ITEM_RE.finditer(text))
    items = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        block = text[match.start():end]
        priority = PRIORITY_RE.search(block)
        automation = AUTOMATION_RE.search(block)
        qa = f'QA-{match.group(1)}-{match.group(2)}'
        if not priority:
            raise ValueError(f'{qa} has no Priority row')
        if not automation:
            raise ValueError(f'{qa} has no Automation row')
        items.append({
            'qa': qa,
            'area': match.group(1),
            'priority': priority.group(1),
            'automation': automation_tag(automation.group(1)),
        })
    return items


def coverage(items: list[dict[str, str]]) -> dict[str, collections.Counter]:
    rows = {area: collections.Counter() for area in AREA_ORDER}
    for item in items:
        area = item['area']
        if area not in rows:
            raise ValueError(f"{item['qa']} has unknown area {area!r}")
        rows[area]['items'] += 1
        rows[area][item['priority']] += 1
        rows[area][item['automation']] += 1
    return rows


def render_table(items: list[dict[str, str]]) -> str:
    rows = coverage(items)
    lines = [
        '<!-- Generated by tests/ci/qa_coverage.py; do not edit counts manually. -->',
        '| Area | Name | Items | P0 | P1 | P2 | AUTO | AUTO-REQ | FIXTURE | MANUAL |',
        '|---|---|---:|---:|---:|---:|---:|---:|---:|---:|',
    ]
    totals = collections.Counter()
    for area in AREA_ORDER:
        row = rows[area]
        totals.update(row)
        values = [row['items'], *(row[key] for key in PRIORITIES),
                  *(row[key] for key in AUTOMATION)]
        lines.append(f"| {area} | {AREA_NAMES[area]} | "
                     + ' | '.join(str(value) for value in values) + ' |')
    values = [totals['items'], *(totals[key] for key in PRIORITIES),
              *(totals[key] for key in AUTOMATION)]
    lines.append('| **Total** | | ' + ' | '.join(f'**{value}**' for value in values) + ' |')
    return '\n'.join(lines)


def replace_table(text: str, table: str) -> str:
    match = COVERAGE_RE.search(text)
    if not match:
        raise ValueError('cannot find Coverage table section')
    return text[:match.start(2)] + table + text[match.end(2):]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--write', action='store_true')
    parser.add_argument('path', nargs='?', type=pathlib.Path,
                        default=pathlib.Path('tests/ci/qa-checklist.md'))
    args = parser.parse_args()
    if args.check and args.write:
        parser.error('--check and --write are mutually exclusive')

    text = args.path.read_text()
    items = parse_items(text)
    table = render_table(items)
    updated = replace_table(text, table)

    if args.write:
        args.path.write_text(updated)
        print(f'updated coverage for {len(items)} QA items in {args.path}')
        return 0
    if args.check:
        if updated != text:
            current = COVERAGE_RE.search(text).group(2)
            print('QA coverage table is stale:', file=sys.stderr)
            print('\n'.join(difflib.unified_diff(
                current.splitlines(), table.splitlines(),
                fromfile='current', tofile='generated', lineterm='')), file=sys.stderr)
            return 1
        print(f'QA coverage table matches {len(items)} QA items')
        return 0

    print(table)
    return 0


if __name__ == '__main__':
    sys.exit(main())
